- type: log
  paths:
    - /home/tomcat/server/MyServer/logs/*catalina.out
  fields:
    module_name: MyServer
    log_type: process
  tags: ["MyServer","backend_process"]
  multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after

- type: log
  paths:
    - /home/tomcat/server/MyServer/logs/*gc.log*
  ignore_older: 24h
  fields:
    module_name: MyServer
    log_type: gc
  tags: ["MyServer","backend_gc"]

- type: log
  paths:
    - /home/tomcat/server/MyServer/logs/*access_log*
  ignore_older: 24h
  fields:
    module_name: MyServer
    log_type: access
  tags: ["MyServer","backend_access"]
