- type: log
  paths:
    - /home/tomcat/server/MyServer/logs/*catalina.out
  fields:
    module_name: MyServer
    log_type: process
  tags: ["MyServer","process"]
  multiline.pattern: '^[[:space:]]|^#|^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after

- type: log
  paths:
    - /home/tomcat/server/MyServer/logs/*gc.log*
  fields:
    module_name: MyServer
    log_type: gc
  tags: ["MyServer","gc"]

- type: log
  paths:
    - /home/tomcat/server/MyServer/logs/*access_log*
  fields:
    module_name: MyServer
    log_type: access
  tags: ["MyServer","access"]
