filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  inputs:
    path: ${path.config}/inputs.d/*.yml
    reload.enabled: true

fields:
  env: lab

tags: ["lab"]

output.logstash:
  hosts: ["logstash:9602"]
