name: AppServer
id: 385
description: 申復爭議 Server migration
ssh_url_to_repo: git@gitlab.tzuchi-healthcare.org.tw:tzuchi_his_source_grp/AppServer.git
web_url: http://gitlab.tzuchi-healthcare.org.tw/tzuchi_his_source_grp/AppServer