name: CodServer
id: 363
description: 疾病分類 Servre migration
ssh_url_to_repo: git@gitlab.tzuchi-healthcare.org.tw:tzuchi_his_source_grp/CodServer.git
web_url: http://gitlab.tzuchi-healthcare.org.tw/tzuchi_his_source_grp/CodServer