- hosts: elasticsearch
  become: yes
  tasks:
  - name: 設定 jvm 的記憶體使用
    lineinfile:
      path: /etc/elasticsearch/jvm.options
      regexp: '^{{ item }}'
      line: '{{ item }}8g'
      backup: yes
    loop:
      - '-Xms'
      - '-Xmx'

    # 用template設定cluster
  # - name: 設定ElasticSearch集群
  #   template:
  #     src: elasticsearch.yml.j2
  #     dest: /etc/elasticsearch/elasticsearch.yml
  #   become: yes

  - name: 重啟ELK
    service:
      name: elasticsearch
      state: restarted
      enabled: yes
