- hosts: logstash
  become: yes
  tasks:
    - name: copy logstash config
      copy:
        src: templates/logstash.yml
        dest: /etc/logstash/logstash.yml

    - name: copy pipeline config
      copy:
        src: templates/backend_process_log.conf
        dest: /etc/logstash/conf.d/backend_process_log.conf

    - name: restart logstash
      service:
        name: logstash
        state: restarted
        enabled: yes
