- hosts: linux-ap-vm
  tasks:
  - name: copy filebeat
    copy:
      src: files/filebeat-7.3.0-x86_64.rpm
      dest: filebeat-7.3.0-x86_64.rpm

  - name: install filebeat and tomcat
    yum:
      name: filebeat-7.3.0-x86_64.rpm
    become: yes
