- hosts: filebeat
  become: yes
  tasks:
    - name: register elasticsearch 6.x repo
      yum_repository:
        name: elasticsearch-6.x
        description: "Elasticsearch repository for 6.x packages"
        baseurl: "https://artifacts.elastic.co/packages/6.x/yum"
        gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        gpgcheck: yes
        state: present
    - name: install filebeat
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - filebeat
        - java-1.8.0
    - name: start filebeat service
      service:
        name: filebeat
        state: started
        enabled: yes