- hosts: elastic
  become: yes
  tasks:
    - name: register elasticsearch 6.x repo
      yum_repository:
        name: elasticsearch-6.x
        description: "Elasticsearch repository for 6.x packages"
        baseurl: "https://artifacts.elastic.co/packages/6.x/yum"
        gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        gpgcheck: yes
        state: present
    - name: install elasticsearch
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - elasticsearch
        - java-1.8.0
    - name: start elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: yes
    - name: config elastic
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: 0660
