- hosts: all
  become: yes
  vars:
    basic_packages:
      - epel-release
      - jdk-8u221-linux-x64.rpm
  tasks:
  - name: copy jdk
    copy: 
      src: files/jdk-8u221-linux-x64.rpm
      dest: jdk-8u221-linux-x64.rpm

  - name: install basic package
    yum:
      name: "{{ item }}"
      state: latest
    loop: "{{ basic_packages }}"
    
- hosts: elasticsearch
  become: yes
  vars:
    elk_packages:
      - elasticsearch-7.3.0-x86_64.rpm
  tasks:
  - name: copy elasticsearch package
    copy:
      src: "files/{{ item }}"
      dest: "{{ item }}"
    loop: "{{ elk_packages }}"

  - name: install elasticsearch
    yum:
      name: "{{ item }}"
    loop: "{{ elk_packages }}"

- hosts: dashboard
  become: yes
  vars: 
    dashboard_packages:
      - logstash-7.3.0.rpm
      - kibana-7.3.0-x86_64.rpm
  tasks:
  - name: copy package
    copy:
      src: "files/{{ item }}"
      dest: "{{ item }}"
    loop: "{{ dashboard_packages }}"

  - name: install 
    yum:
      name: "{{ item }}"
    loop: "{{ dashboard_packages }}"

- hosts: ap
  become: yes
  vars:
    ap_packages:
      - tomcat
      - filebeat-7.3.0-x86_64.rpm
  tasks:
  - name: copy 
    copy:
      src: files/filebeat-7.3.0-x86_64.rpm
      dest: filebeat-7.3.0-x86_64.rpm
 
  - name: install
    yum: 
      name: "{{ item }}"
    loop: "{{ ap_packages }}"