filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/tsengeagle/*_catalina.out
  fields:
    env: tp-prod
    app_module: SecServer
  multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
setup.kibana:

fields:
  end: tp-prod

output.logstash:
  hosts: ["10.2.145.16:9600"]
  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
