filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    paths:
      - /var/log/messages
      - /var/log/*.log

  - type: log
    paths:
      - /home/tomcat/server/**/*.out
    fields:
      log_type: backend_process_log
    multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
    multiline.negate: false
    multiline.match: after

  - type: log
    paths:
      - /home/tomcat/server/MyServer/**/*gc.log*
    ignore_older: 24h
    fields:
      log_type: backend_gc_log

  - type: log
    paths:
      - /home/tomcat/server/**/*access_log*
    ignore_older: 24h
    fields:
      log_type: backend_access_log
    exclude_lines: ['^10.2.145.1','(^10.2.105.22)(.*)(HEAD)'] #排除監控系統的存取紀錄

fields:
  env: tp-prod

output.logstash:
  hosts: ["10.2.145.16:9602"]
