filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  inputs:
    path: ${path.config}/inputs.d/*.yml
    reload.enabled: true

filebeat.inputs:
  - type: log
    paths:
      - /var/log/messages
    tags: ["system_log"]

fields:
  env: {{ env_name }}

output.logstash:
  hosts: ["{{ output_host  }}:{{ output_port }}"]

