filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  inputs:
    path: ${path.config}/inputs.d/*.yml
    reload.enabled: true

fields:
  env: {{ env_name }}

output.logstash:
  hosts: ["{{ output_host  }}:{{ output_port }}"]

