package_source: "http://10.2.145.150:8081/artifactory/his5/package"
java: "java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64.rpm"
tomcat: "apache-tomcat-8.0.39.tar.gz"
java_agent: "jmx_prometheus_javaagent-0.3.1.jar"

min_memory: 4000
max_memory: 4000
ap_environment: "tp-intt"
ap_root: "/home/tomcat/server"

release_repo: "http://10.2.145.150:8081/artifactory"
release_path: "his5/war"

yum_proxy: yes

special_server:
  - name: hrpserver
    ip: 10.2.105.43
  - name: TzuchiServer
    ip: 10.2.105.73
  - name: FileServer
    ip: 10.2.105.81
  - name: ReportServer
    ip: 10.2.105.83
  - name: APL03
    ip: 10.2.105.73
  - name: APL11
    ip: 10.2.105.81
  - name: APW01
    ip: 10.2.105.83
  - name: his-db
    ip: 10.2.105.90
  - name: rpt-db
    ip: 10.2.105.91


file_server: 10.2.127.111

service_type: openjdk
gc_param:
gc_type: cms_gc

g1_gc: '-XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:PatallelGCThreads=8 -XX:GoncGCThreads=2 -XX:InitiatingHeapOccupancyPercent=45'
cms_gc: "-XX:PermSize={{ min_perm | int }}m -XX:MaxPermSize={{ max_perm | int }}m -XX:NewSize={{ min_new | int }}m -XX:MaxNewSize={{ max_new | int }}m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=50 -XX:+UseCMSInitiatingOccupancyOnly -XX:+CMSParallelRemarkEnabled -Djava.awt.headless=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+PrintGCDetails -XX:+PrintGCDateStamps"

min_perm: "{{ min_memory * 0.2 }}"
max_perm: "{{ max_memory * 0.3 }}"
min_new: "{{ min_memory * 0.3 }}"
max_new: "{{ max_memory * 0.4 }}"
